# Kanso Ink Alacritty Colors

[colors.primary]
background = '#14171d'
foreground = '#C5C9C7'

[colors.normal]
black = '#14171d'
red = '#c4746e'
green = '#ffdd00'
yellow = '#c4b28a'
blue = '#ffffff'
magenta = '#a292a3'
cyan = '#ffffcc'
white = '#c8c093'

[colors.bright]
black = '#A4A7A4'
red = '#e46876'
green = '#ffee44'
yellow = '#e6c384'
blue = '#ffff14'
magenta = '#938aa9'
cyan = '#fff000'
white = '#C5C9C7'

[colors.selection]
background = '#393B44'
foreground = '#C5C9C7'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'
